version: "3.8"

volumes:
  rabbitmq_data:

services:
 
  #######################################################
  # Schedule Record: The Schedule microservice
  #######################################################
  schedule:
    build:
      context: ./
      dockerfile: schedule.Dockerfile
    image: xinwei0607/schedule:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1

  #######################################################
  # Appointment Record: The Appointmen microservice
  #######################################################
  appointment:
    build:
      context: ./
      dockerfile: appointment.Dockerfile
    image: xinwei0607/appointment:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1

  ###################################
  # Patient: The patient microservice
  ###################################
  patient:
    build:
      context: ./
      dockerfile: patient.Dockerfile
    image: xinwei0607/patient:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/order
      PYTHONUNBUFFERED: 1

  ###################################
  # Book Appointment: The book_appt microservice
  ###################################
  book_appt:
    build:
      context: ./
      dockerfile: book_appt.Dockerfile
    image: xinwei0607/book_appt:esd
    restart: always
    depends_on:
      - schedule
      - appointment
      - patient
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/order
      PYTHONUNBUFFERED: 1

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
      
  #################################################
  #  Medicine: The Medicine microservice
  #################################################
  medicine:
    build:
      context: ./
      dockerfile: medicine.Dockerfile
    image: xinwei0607/medicine:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  #################################################
  #  Queue: The Queue microservice
  #################################################
  queue:
    build:
      context: ./
      dockerfile: queue.Dockerfile
    image: xinwei0607/queue:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1  

  ###################################
  # Patient Removal: The patient removal microservice
  ###################################
  patientremoval:
    build:
      context: ./
      dockerfile: patientremoval.Dockerfile
    image: xinwei0607/patientremoval:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/order
      PYTHONUNBUFFERED: 1

  ###################################
  # Prescribe Medicine: The Prescribe Medicine microservice
  ###################################
  prescribe_medicine:
    build:
      context: ./
      dockerfile: prescribe_medicine.Dockerfile
    image: xinwei0607/prescribe_medicine:esd
    restart: always
    depends_on:
      - medicine
      - queue
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/prescribe_medicine
      PYTHONUNBUFFERED: 1
      rabbit_host: rabbitmq
      rabbit_port: 5672
      queue_URL: 'http://127.0.0.1:5004/queue'
      medicine_URL: 'http://127.0.0.1:8000/medicine'

  ###################################
  # Payment: The patient removal microservice
  ###################################
  paymentService:
    build:
      context: ./
      dockerfile: paymentService.Dockerfile
    image: xinwei0607/paymentservice:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/order
      PYTHONUNBUFFERED: 1

  ###################################
  # Make Payment: The Make Payment microservice
  ###################################
  paypal:
    build:
      context: ./
      dockerfile: paypal.Dockerfile
    image: xinwei0607/paypal:esd
    restart: always
    depends_on:
      - paymentService
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/order
      PYTHONUNBUFFERED: 1



  